// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package storage

import (
	"context"
	"github.com/murdho/playlists-by-tallinn/firestore"
	"sync"
)

var (
	lockFirestoreMockGet sync.RWMutex
	lockFirestoreMockSet sync.RWMutex
)

// Ensure, that FirestoreMock does implement Firestore.
// If this is not the case, regenerate this file with moq.
var _ Firestore = &FirestoreMock{}

// FirestoreMock is a mock implementation of Firestore.
//
//     func TestSomethingThatUsesFirestore(t *testing.T) {
//
//         // make and configure a mocked Firestore
//         mockedFirestore := &FirestoreMock{
//             GetFunc: func(ctx context.Context, dataTo interface{}, documentID string, opts ...firestore.Option) error {
// 	               panic("mock out the Get method")
//             },
//             SetFunc: func(ctx context.Context, documentID string, data interface{}, opts ...firestore.Option) error {
// 	               panic("mock out the Set method")
//             },
//         }
//
//         // use mockedFirestore in code that requires Firestore
//         // and then make assertions.
//
//     }
type FirestoreMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, dataTo interface{}, documentID string, opts ...firestore.Option) error

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, documentID string, data interface{}, opts ...firestore.Option) error

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DataTo is the dataTo argument value.
			DataTo interface{}
			// DocumentID is the documentID argument value.
			DocumentID string
			// Opts is the opts argument value.
			Opts []firestore.Option
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID string
			// Data is the data argument value.
			Data interface{}
			// Opts is the opts argument value.
			Opts []firestore.Option
		}
	}
}

// Get calls GetFunc.
func (mock *FirestoreMock) Get(ctx context.Context, dataTo interface{}, documentID string, opts ...firestore.Option) error {
	if mock.GetFunc == nil {
		panic("FirestoreMock.GetFunc: method is nil but Firestore.Get was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		DataTo     interface{}
		DocumentID string
		Opts       []firestore.Option
	}{
		Ctx:        ctx,
		DataTo:     dataTo,
		DocumentID: documentID,
		Opts:       opts,
	}
	lockFirestoreMockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	lockFirestoreMockGet.Unlock()
	return mock.GetFunc(ctx, dataTo, documentID, opts...)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedFirestore.GetCalls())
func (mock *FirestoreMock) GetCalls() []struct {
	Ctx        context.Context
	DataTo     interface{}
	DocumentID string
	Opts       []firestore.Option
} {
	var calls []struct {
		Ctx        context.Context
		DataTo     interface{}
		DocumentID string
		Opts       []firestore.Option
	}
	lockFirestoreMockGet.RLock()
	calls = mock.calls.Get
	lockFirestoreMockGet.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *FirestoreMock) Set(ctx context.Context, documentID string, data interface{}, opts ...firestore.Option) error {
	if mock.SetFunc == nil {
		panic("FirestoreMock.SetFunc: method is nil but Firestore.Set was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		DocumentID string
		Data       interface{}
		Opts       []firestore.Option
	}{
		Ctx:        ctx,
		DocumentID: documentID,
		Data:       data,
		Opts:       opts,
	}
	lockFirestoreMockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	lockFirestoreMockSet.Unlock()
	return mock.SetFunc(ctx, documentID, data, opts...)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//     len(mockedFirestore.SetCalls())
func (mock *FirestoreMock) SetCalls() []struct {
	Ctx        context.Context
	DocumentID string
	Data       interface{}
	Opts       []firestore.Option
} {
	var calls []struct {
		Ctx        context.Context
		DocumentID string
		Data       interface{}
		Opts       []firestore.Option
	}
	lockFirestoreMockSet.RLock()
	calls = mock.calls.Set
	lockFirestoreMockSet.RUnlock()
	return calls
}
